### PR TITLE
Update mrv2_translations.nsh

### PR DESCRIPTION
**Pull request by bovirus**
@ggarra13 

Update Italian language strings.

Could you please enable me to translate other part in italian 

adding here

https://github.com/ggarra13/mrv2/tree/main/mrv2/po/python/plug-ins/locale

a folder it/LC_MESSAGES

where can i upaaod the update-mrv2.po

Thanks.

### CODE REVIEW

**Comment by ggarra13** [comment]
Thank you very much for your contribution!

**Comment by ggarra13** [comment]
For tranlating other parts in Italian, you should create a fork of mrv2 under your name with github.

There are GitHub docs, e.g.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

In a nutshell:

- fork the mrv2 repo to e.g. your-username/mrv2
- create a feature branch in you fork (important although not required [1])
- push one or more commits to your feature branch
- request a PR on your repo/feature-branch

[1] If you didn't create your own feature-branch you'd push to "your"
master branch which is not recommended for some reasons. It's hard to
maintain for developers.

Also, see:

https://github.com/ggarra13/mrv2#translating

**Comment by bovirus** [comment]
@ggarra13 

Please create it/LC_MESSAGES in this source path

/mrv2/po/python/plug-ins/locale

where can i upload the language file.

**Comment by ggarra13** [comment]
Git, which is the service for files that uses GitHub, does not allow creating empty directories.  
Just rename the files to:

it.po.txt                                    # if you translated **all** of mrv2
update-mrv2.po.txt               # if you translated just the python update-mrv2.py plug-in.

and attach them to this thread.  Use the "Clip" button at the top of the add comment or "Paste, drop or click to add files" at the bottom of the comment.

**Comment by bovirus** [comment]
@ggarra13 

You can create teh directory and copy then tehn english file renamed for italian.

Then this is the update-mrv2.po file

[update-mrv2.po.txt](https://github.com/user-attachments/files/15847869/update-mrv2.po.txt)

**Pull request merged**
