### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Thane5**
I made a banner. Just felt like the readme could use some color.

### CODE REVIEW

**Comment by ggarra13** [comment]
The banner is hosted on github on your repository link.  While usually safe, it may disappear if GitHub makes changes to its policies of holding images.  Please place it somewhere in your mrv2 repositoty, like:

${ROOT}/mrv2/etc/mrv2_banner.png

and refer to it relative to it from the main README.md.

**Comment by ggarra13** [comment]
Merged.

**Comment by Thane5** [comment]
Sorry, i couldn't revise this in time. 

I also just now noticed that you used the tagline "The Professional Flipbook, Video and Audio Player" on your sourceforge site. Would you prefer if i use that insteead of my somwhat improvised "Frame by Frame, Pixel by Pixel"?

**Comment by ggarra13** [comment]
Don't worry!  I like your tag of Frame by Frame and Pixel by Pixel!!!  It is much less pompous and pretencious than "Professional blah, blah, blah...".

**Pull request closed without merging**
